# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, ekgCore, network, text, time, unorderedContainers }:

cabal.mkDerivation (self: {
  pname = "ekg-statsd";
  version = "0.2.0.1";
  sha256 = "0s01bkir41189ss72sshlbg4y4qk2wvkr234m2j1y0169l067687";
  buildDepends = [ ekgCore network text time unorderedContainers ];
  meta = {
    homepage = "https://github.com/tibbe/ekg-statsd";
    description = "Push metrics to statsd";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
