# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, HsOpenSSL, hspec, httpClient, httpTypes, network }:

cabal.mkDerivation (self: {
  pname = "http-client-openssl";
  version = "0.2.0.1";
  sha256 = "1mg2gn51ixb68wd8mm66kcj4627q6gj64810wsa1axy3jmk5qym3";
  buildDepends = [ HsOpenSSL httpClient network ];
  testDepends = [ HsOpenSSL hspec httpClient httpTypes ];
  meta = {
    homepage = "https://github.com/snoyberg/http-client";
    description = "http-client backend using the OpenSSL library";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
